In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create arr 1-dimensional NumPy array using np.array()
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [3]:
# Create arr 2-dimensional NumPy array using np.array()
arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [4]:
# Create arr 3-dimensional NumPy array using np.array()
arr3 = np.array(
    [
        [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]],
        [[16, 17, 18, 19, 20], [21, 22, 23, 24, 25], [26, 27, 28, 29, 30]],
    ]
)
arr3

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])

In [5]:
# Attributes of 1-dimensional array
arr1.shape, arr1.ndim, arr1.dtype, arr1.size, type(arr1)

((5,), 1, dtype('int32'), 5, numpy.ndarray)

In [6]:
# Attributes of 2-dimensional array
arr2.shape, arr2.ndim, arr2.dtype, arr2.size, type(arr2)

((2, 5), 2, dtype('int32'), 10, numpy.ndarray)

In [7]:
# Attributes of 3-dimensional array
arr3.shape, arr3.ndim, arr3.dtype, arr3.size, type(arr3)

((2, 3, 5), 3, dtype('int32'), 30, numpy.ndarray)

In [8]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df = pd.DataFrame(arr2)
df

0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10

In [9]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((5, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [11]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0, 100, 3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [12]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(10, 100, size=(5, 7))
print("Random Integers:\n", random_array)

Random Integers:
 [[71 89 81 88 38 62 68]
 [65 84 43 87 67 18 35]
 [19 56 25 96 88 37 67]
 [75 58 81 67 60 66 59]
 [39 95 59 14 85 35 68]]


In [13]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_decimal = np.random.random(size=(3, 5))
print("Random Decimal:\n", random_decimal)

Random Decimal:
 [[0.66284365 0.88337548 0.10663214 0.6678364  0.56588257]
 [0.589318   0.65374229 0.96760869 0.81107929 0.68953159]
 [0.46543838 0.78278737 0.66257262 0.84829186 0.20903059]]


In [14]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(10, size=(4, 6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [15]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
arr = np.random.randint(15, 30, size=(5, 3))
arr

array([[27, 26, 23],
       [15, 25, 25],
       [29, 24, 26],
       [26, 29, 28],
       [28, 29, 28]])

In [16]:
# Find the unique numbers in the array you just created
np.unique(arr)

array([15, 23, 24, 25, 26, 27, 28, 29])

In [17]:
# Find the 0'th index of the latest array you created
arr[0]

array([27, 26, 23])

In [18]:
# Get the first 2 rows of latest array you created
arr[:2]

array([[27, 26, 23],
       [15, 25, 25]])

In [19]:
# Get the first 2 values of the first 2 rows of the latest array
arr[:2, :2]

array([[27, 26],
       [15, 25]])

In [20]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arr4 = np.random.randint(15, size=(3, 5))
arr4

array([[ 2, 11,  6,  3,  8],
       [ 2,  4,  2,  6,  4],
       [ 8,  6,  1,  3,  8]])

In [21]:
ones = np.ones((3, 5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
arr4 + ones

array([[ 3., 12.,  7.,  4.,  9.],
       [ 3.,  5.,  3.,  7.,  5.],
       [ 9.,  7.,  2.,  4.,  9.]])

In [23]:
arr4 - ones

array([[ 1., 10.,  5.,  2.,  7.],
       [ 1.,  3.,  1.,  5.,  3.],
       [ 7.,  5.,  0.,  2.,  7.]])

In [24]:
arr4 * ones

array([[ 2., 11.,  6.,  3.,  8.],
       [ 2.,  4.,  2.,  6.,  4.],
       [ 8.,  6.,  1.,  3.,  8.]])

In [25]:
arr4 / ones

array([[ 2., 11.,  6.,  3.,  8.],
       [ 2.,  4.,  2.,  6.,  4.],
       [ 8.,  6.,  1.,  3.,  8.]])

In [26]:
arr4 % ones

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
arr4**ones

array([[ 2., 11.,  6.,  3.,  8.],
       [ 2.,  4.,  2.,  6.,  4.],
       [ 8.,  6.,  1.,  3.,  8.]])

In [28]:
# like ** but still focus
np.square(arr4)

array([[  4, 121,  36,   9,  64],
       [  4,  16,   4,  36,  16],
       [ 64,  36,   1,   9,  64]])

In [29]:
np.mean(arr4)

4.933333333333334

In [30]:
np.max(arr4)

11

In [31]:
np.min(arr4)

1

In [32]:
np.std(arr4)

2.815828277592383

In [33]:
# # Find the variance of the latest array
np.var(arr4)

7.9288888888888875

In [34]:
arr4.reshape(5, 3, 1)

array([[[ 2],
        [11],
        [ 6]],

       [[ 3],
        [ 8],
        [ 2]],

       [[ 4],
        [ 2],
        [ 6]],

       [[ 4],
        [ 8],
        [ 6]],

       [[ 1],
        [ 3],
        [ 8]]])

In [35]:
arr4

array([[ 2, 11,  6,  3,  8],
       [ 2,  4,  2,  6,  4],
       [ 8,  6,  1,  3,  8]])

In [36]:
arr4.T

array([[ 2,  2,  8],
       [11,  4,  6],
       [ 6,  2,  1],
       [ 3,  6,  3],
       [ 8,  4,  8]])

In [37]:
# Create another array of ones of shape (5, 3)
ones = np.ones((5, 3)).T
arr4 + ones

array([[ 3., 12.,  7.,  4.,  9.],
       [ 3.,  5.,  3.,  7.,  5.],
       [ 9.,  7.,  2.,  4.,  9.]])

In [38]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
mat1 = np.random.randint(10, size=(3, 3))
mat1

array([[1, 9, 8],
       [9, 4, 1],
       [3, 6, 7]])

In [39]:
mat2 = np.random.randint(10, size=(3, 2))
mat2

array([[2, 0],
       [3, 1],
       [7, 3]])

In [40]:
# Perform a dot product on the two newest arrays you created
np.dot(mat1, mat2)

array([[85, 33],
       [37,  7],
       [73, 27]])

In [41]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
mat3 = np.random.randint(10, size=(4, 3))
mat4 = np.random.randint(10, size=(3, 4))

print("Matriks 3 (4x3):")
print(mat3)

print("\nMatriks 4 (3x4):")
print(mat4)

result = np.dot(mat3, mat4)
print("\nHasil dari np.dot(mat3, mat4):")
print(result)

Matriks 3 (4x3):
[[1 5 5]
 [9 3 5]
 [1 9 1]
 [9 3 7]]

Matriks 4 (3x4):
[[6 8 7 4]
 [1 4 7 9]
 [8 8 0 8]]

Hasil dari np.dot(mat3, mat4):
[[ 51  68  42  89]
 [ 97 124  84 103]
 [ 23  52  70  93]
 [113 140  84 119]]


In [42]:
mat5 = np.random.randint(10, size=(4, 2))
mat5

array([[6, 8],
       [7, 0],
       [7, 7],
       [2, 0]])

In [43]:
mat6 = np.random.randint(10, size=(4, 2))
mat6

array([[7, 2],
       [2, 0],
       [4, 9],
       [6, 9]])

In [44]:
mat5 > mat6

array([[False,  True],
       [ True, False],
       [ True, False],
       [False, False]])

In [45]:
mat5 >= mat6

array([[False,  True],
       [ True,  True],
       [ True, False],
       [False, False]])

In [46]:
mat5 > 7

array([[False,  True],
       [False, False],
       [False, False],
       [False, False]])

In [47]:
mat5 == mat6

array([[False, False],
       [False,  True],
       [False, False],
       [False, False]])

In [48]:
np.sort(mat5)

array([[6, 8],
       [0, 7],
       [7, 7],
       [0, 2]])

In [49]:
argsort = np.argsort(mat6)
argmax = np.argmax(mat6)
argmin = np.argmin(mat6)
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
axis1 = np.argmax(mat6, axis=1)
axis2 = np.argmin(mat6, axis=0)

print("argsort:\n", argsort)
print("\nargmax:", argmax)
print("\nargmin:", argmin)
print("\naxis1:", axis1)
print("\naxis2:", axis2)

argsort:
 [[1 0]
 [1 0]
 [0 1]
 [0 1]]

argmax: 5

argmin: 3

axis1: [0 0 1 1]

axis2: [1 1]


In [50]:
# Create an array of normally distributed random numbers
np.random.randn(3, 5)

array([[-1.50815329,  1.09964698, -0.17773212, -0.41038331,  1.17971634],
       [-0.89820794,  0.83479542,  0.29656138, -1.03782988, -0.07580375],
       [ 0.97296353,  0.79559546,  1.49543425,  0.33818125,  3.37229625]])

In [51]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])